# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCA', models.CharField(max_length=69)),
                ('percentage', models.IntegerField()),
                ('college', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=300)),
                ('summary', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='keySkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(max_length=40)),
                ('duration', models.IntegerField()),
                ('instructor', models.CharField(max_length=30)),
            ],
        ),
    ]
