# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-02 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='MCA',
            new_name='Qualification',
        ),
    ]
