# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-02 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200102_1233'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personal_Profile',
            new_name='Profile',
        ),
    ]
